INSERT INTO attractions (
  name, city, address, category, description, latitude, longitude,
  duration_minutes, budget_level, rating, image_url, tags
) VALUES
(
  'Национальная библиотека Беларуси',
  'Минск',
  'проспект Независимости, 116',
  'architecture',
  'Современный символ Минска с обзорной площадкой и вечерней подсветкой.',
  53.931111,
  27.646389,
  75,
  'mid',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Minsk_Belarus_National-Library_41_%2851925255820%29.jpg?width=900',
  ARRAY['панорама', 'архитектура', 'город']
),
(
  'Верхний город',
  'Минск',
  'площадь Свободы',
  'history',
  'Исторический центр города с ратушей, храмами, двориками и кафе.',
  53.903900,
  27.556900,
  90,
  'free',
  4.7,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Minsk_Town_Hall_20190502.jpg?width=900',
  ARRAY['история', 'прогулка', 'центр']
),
(
  'Троицкое предместье',
  'Минск',
  'улица Старовиленская',
  'culture',
  'Камерный квартал у Свислочи с музеями, набережной и старой застройкой.',
  53.908611,
  27.556667,
  80,
  'free',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Former_Cloister_of_Holy_Trinity%2C_Minsk.JPG?width=900',
  ARRAY['культура', 'набережная', 'фото']
),
(
  'Парк Победы',
  'Минск',
  'проспект Победителей',
  'nature',
  'Большой городской парк у Комсомольского озера для спокойных прогулок.',
  53.920800,
  27.535700,
  110,
  'free',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/View_of_Victory_Park_Minsk.jpg?width=900',
  ARRAY['природа', 'озеро', 'прогулка']
),
(
  'Музей истории Великой Отечественной войны',
  'Минск',
  'проспект Победителей, 8',
  'history',
  'Один из крупнейших музеев страны с современной экспозицией.',
  53.916900,
  27.537900,
  120,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Minsk_Kriegsmuseum.JPG?width=900',
  ARRAY['музей', 'история', 'экспозиция']
),
(
  'Ботанический сад',
  'Минск',
  'улица Сурганова, 2в',
  'nature',
  'Зелёная территория для сезонных прогулок, оранжерей и спокойного отдыха.',
  53.917700,
  27.608000,
  100,
  'low',
  4.7,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Phlox_in_Botanical_garden%2C_Minsk.jpg?width=900',
  ARRAY['природа', 'растения', 'семья']
),
(
  'Остров слёз',
  'Минск',
  'Остров Мужества и Скорби',
  'history',
  'Мемориальный комплекс рядом с Троицким предместьем.',
  53.910500,
  27.554700,
  35,
  'free',
  4.5,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Island_of_Tears.jpg?width=900',
  ARRAY['мемориал', 'история', 'центр']
),
(
  'Зыбицкая улица',
  'Минск',
  'улица Зыбицкая',
  'food',
  'Популярная улица с кафе, барами и вечерней городской атмосферой.',
  53.905900,
  27.558300,
  70,
  'high',
  4.4,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Ulitsa_Zybitskaya_Minsk.JPG?width=900',
  ARRAY['еда', 'вечер', 'центр']
),
(
  'Мирский замок',
  'Мир',
  'улица Красноармейская, 2',
  'history',
  'Замковый комплекс XVI века с башнями, внутренним двором и парком.',
  53.451300,
  26.472400,
  130,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/MIR_CASTLE_-_BELARUS.jpg?width=900',
  ARRAY['замок', 'история', 'архитектура']
),
(
  'Несвижский замок',
  'Несвиж',
  'улица Замковая, 2',
  'architecture',
  'Дворцово-парковый ансамбль Радзивиллов с музеем, валами и прудами.',
  53.222600,
  26.691100,
  150,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Nesvizh_Castle_2011.JPG?width=900',
  ARRAY['замок', 'парк', 'архитектура']
),
(
  'Брестская крепость',
  'Брест',
  'улица Героев обороны Брестской крепости',
  'history',
  'Мемориальный комплекс с монументами, музеями и сохранившимися укреплениями.',
  52.082800,
  23.656400,
  140,
  'free',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Brestfortress02.JPG?width=900',
  ARRAY['мемориал', 'история', 'музей']
),
(
  'Беловежская пуща',
  'Каменюки',
  'Национальный парк Беловежская пуща',
  'nature',
  'Древний лесной массив с экологическими тропами, зубрами и природными маршрутами.',
  52.557000,
  23.802000,
  180,
  'mid',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Belovezhskaya_Pushcha_N.P.jpg?width=900',
  ARRAY['природа', 'лес', 'семья']
),
(
  'Софийский собор',
  'Полоцк',
  'улица Замковая, 1',
  'culture',
  'Один из главных историко-культурных символов Полоцка с концертным залом.',
  55.485600,
  28.758600,
  90,
  'low',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/%D0%A1%D0%B0%D1%84%D1%96%D0%B9%D1%81%D0%BA%D1%96_%D1%81%D0%B0%D0%B1%D0%BE%D1%80%2C_%D0%9F%D0%BE%D0%BB%D0%B0%D1%86%D0%BA.jpg?width=900',
  ARRAY['собор', 'культура', 'история']
),
(
  'Лидский замок',
  'Лида',
  'улица Замковая, 1',
  'history',
  'Средневековый замок князя Гедимина, восстановленный для экскурсий и событий.',
  53.887500,
  25.302900,
  95,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/The_Lida_castle.JPG?width=900',
  ARRAY['замок', 'история', 'архитектура']
),
(
  'Мемориальный комплекс Хатынь',
  'Логойский район',
  'Хатынь',
  'history',
  'Мемориал на месте сожжённой деревни, посвящённый памяти жертв войны.',
  54.334600,
  27.943200,
  90,
  'free',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Khatyn%2C_Belarus_5.jpg?width=900',
  ARRAY['мемориал', 'история', 'память']
),
(
  'Гомельский дворцово-парковый ансамбль',
  'Гомель',
  'площадь Ленина, 4',
  'architecture',
  'Дворец Румянцевых и Паскевичей с парком, набережной Сожа и музейными залами.',
  52.422600,
  31.015900,
  120,
  'mid',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Gomel-dvorets_Rumyantsevyh-Paskevichei_-_zima2008.JPG?width=900',
  ARRAY['дворец', 'парк', 'архитектура']
),
(
  'Августовский канал',
  'Гродненский район',
  'Августовский канал',
  'nature',
  'Водно-парковый маршрут с шлюзами, лесами и прогулками вдоль канала.',
  53.862000,
  23.623200,
  150,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Augustow_Canal_IMG_1384_2175.jpg?width=900',
  ARRAY['природа', 'вода', 'прогулка']
),
(
  'Браславские озёра',
  'Браслав',
  'Национальный парк Браславские озёра',
  'nature',
  'Озёрный край с обзорными точками, тропами и спокойными природными маршрутами.',
  55.643000,
  27.040000,
  180,
  'low',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Belarus%2C_Braslav_lakes%2C_Strusto_1.jpg?width=900',
  ARRAY['озёра', 'природа', 'панорама']
),
(
  'Гродненский Старый замок',
  'Гродно',
  'улица Замковая, 22',
  'history',
  'Исторический замок над Неманом с музейной экспозицией и видами на город.',
  53.678400,
  23.823100,
  100,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Grodno_Old_Castle_11166_2150.jpg?width=900',
  ARRAY['замок', 'история', 'музей']
),
(
  'Витебская ратуша',
  'Витебск',
  'улица Ленина, 36',
  'architecture',
  'Историческая ратуша в центре Витебска, где расположен областной краеведческий музей.',
  55.194700,
  30.206900,
  80,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Vitebsk_cityhall_oct_2005.jpg?width=900',
  ARRAY['ратуша', 'архитектура', 'музей']
),
(
  'Бобруйская крепость',
  'Бобруйск',
  'улица Карбышева',
  'history',
  'Крупный фортификационный комплекс XIX века с сохранившимися укреплениями.',
  53.137800,
  29.225100,
  85,
  'free',
  4.4,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Bobruisk_fortress.jpg?width=900',
  ARRAY['крепость', 'история', 'прогулка']
),
(
  'Буйничское поле',
  'Могилёв',
  'Буйничское поле',
  'history',
  'Мемориальный комплекс на месте оборонительных боёв под Могилёвом.',
  53.859700,
  30.267600,
  80,
  'free',
  4.5,
  'https://commons.wikimedia.org/wiki/Special:FilePath/%D0%91%D1%83%D0%B9%D0%BD%D0%B8%D1%87%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D0%BE%D0%BB%D0%B5.jpg?width=900',
  ARRAY['мемориал', 'история', 'память']
),
(
  'Меловые карьеры у Волковыска',
  'Волковыск',
  'окрестности Волковыска',
  'nature',
  'Светлые меловые ландшафты и водоёмы, популярные для фотопрогулок.',
  53.151000,
  24.455000,
  90,
  'free',
  4.3,
  'https://commons.wikimedia.org/wiki/Special:FilePath/The_chalkpit_near_Krasnoselsk_-_panoramio.jpg?width=900',
  ARRAY['природа', 'панорама', 'фото']
)
ON CONFLICT (name, city) DO UPDATE SET
  address = EXCLUDED.address,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  duration_minutes = EXCLUDED.duration_minutes,
  budget_level = EXCLUDED.budget_level,
  rating = EXCLUDED.rating,
  image_url = EXCLUDED.image_url,
  tags = EXCLUDED.tags;
