INSERT INTO users (name, email, password_hash, role, preferences)
VALUES (
  'Администратор',
  'admin@tourist.local',
  '$2a$10$3IEwggKEr8HWvkXc1L7eUeAzX.zVjRaHsPkOrojelouofEZwyxJvK',
  'admin',
  '{
    "interests": ["history", "culture", "architecture"],
    "budget": "mid",
    "pace": "balanced",
    "maxDuration": 480
  }'::jsonb
)
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash,
  role = EXCLUDED.role,
  preferences = EXCLUDED.preferences,
  is_active = TRUE,
  updated_at = NOW();

INSERT INTO attractions (
  name, city, address, category, description, latitude, longitude,
  duration_minutes, budget_level, rating, image_url, tags
) VALUES
(
  'Национальная библиотека Беларуси',
  'Минск',
  'проспект Независимости, 116',
  'architecture',
  'Современный символ Минска с обзорной площадкой и вечерней подсветкой.',
  53.931111,
  27.646389,
  75,
  'mid',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Minsk_Belarus_National-Library_41_%2851925255820%29.jpg?width=900',
  ARRAY['панорама', 'архитектура', 'город']
),
(
  'Верхний город',
  'Минск',
  'площадь Свободы',
  'history',
  'Исторический центр города с ратушей, храмами, двориками и кафе.',
  53.903900,
  27.556900,
  90,
  'free',
  4.7,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Minsk_Town_Hall_20190502.jpg?width=900',
  ARRAY['история', 'прогулка', 'центр']
),
(
  'Троицкое предместье',
  'Минск',
  'улица Старовиленская',
  'culture',
  'Камерный квартал у Свислочи с музеями, набережной и старой застройкой.',
  53.908611,
  27.556667,
  80,
  'free',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Former_Cloister_of_Holy_Trinity%2C_Minsk.JPG?width=900',
  ARRAY['культура', 'набережная', 'фото']
),
(
  'Парк Победы',
  'Минск',
  'проспект Победителей',
  'nature',
  'Большой городской парк у Комсомольского озера для спокойных прогулок.',
  53.920800,
  27.535700,
  110,
  'free',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/View_of_Victory_Park_Minsk.jpg?width=900',
  ARRAY['природа', 'озеро', 'прогулка']
),
(
  'Музей истории Великой Отечественной войны',
  'Минск',
  'проспект Победителей, 8',
  'history',
  'Один из крупнейших музеев страны с современной экспозицией.',
  53.916900,
  27.537900,
  120,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Minsk_Kriegsmuseum.JPG?width=900',
  ARRAY['музей', 'история', 'экспозиция']
),
(
  'Ботанический сад',
  'Минск',
  'улица Сурганова, 2в',
  'nature',
  'Зелёная территория для сезонных прогулок, оранжерей и спокойного отдыха.',
  53.917700,
  27.608000,
  100,
  'low',
  4.7,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Phlox_in_Botanical_garden%2C_Minsk.jpg?width=900',
  ARRAY['природа', 'растения', 'семья']
),
(
  'Остров слёз',
  'Минск',
  'Остров Мужества и Скорби',
  'history',
  'Мемориальный комплекс рядом с Троицким предместьем.',
  53.910500,
  27.554700,
  35,
  'free',
  4.5,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Island_of_Tears.jpg?width=900',
  ARRAY['мемориал', 'история', 'центр']
),
(
  'Зыбицкая улица',
  'Минск',
  'улица Зыбицкая',
  'food',
  'Популярная улица с кафе, барами и вечерней городской атмосферой.',
  53.905900,
  27.558300,
  70,
  'high',
  4.4,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Ulitsa_Zybitskaya_Minsk.JPG?width=900',
  ARRAY['еда', 'вечер', 'центр']
),
(
  'Мирский замок',
  'Мир',
  'улица Красноармейская, 2',
  'history',
  'Замковый комплекс XVI века с башнями, внутренним двором и парком.',
  53.451300,
  26.472400,
  130,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/MIR_CASTLE_-_BELARUS.jpg?width=900',
  ARRAY['замок', 'история', 'архитектура']
),
(
  'Несвижский замок',
  'Несвиж',
  'улица Замковая, 2',
  'architecture',
  'Дворцово-парковый ансамбль Радзивиллов с музеем, валами и прудами.',
  53.222600,
  26.691100,
  150,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Nesvizh_Castle_2011.JPG?width=900',
  ARRAY['замок', 'парк', 'архитектура']
),
(
  'Брестская крепость',
  'Брест',
  'улица Героев обороны Брестской крепости',
  'history',
  'Мемориальный комплекс с монументами, музеями и сохранившимися укреплениями.',
  52.082800,
  23.656400,
  140,
  'free',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Brestfortress02.JPG?width=900',
  ARRAY['мемориал', 'история', 'музей']
),
(
  'Беловежская пуща',
  'Каменюки',
  'Национальный парк Беловежская пуща',
  'nature',
  'Древний лесной массив с экологическими тропами, зубрами и природными маршрутами.',
  52.557000,
  23.802000,
  180,
  'mid',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Belovezhskaya_Pushcha_N.P.jpg?width=900',
  ARRAY['природа', 'лес', 'семья']
),
(
  'Софийский собор',
  'Полоцк',
  'улица Замковая, 1',
  'culture',
  'Один из главных историко-культурных символов Полоцка с концертным залом.',
  55.485600,
  28.758600,
  90,
  'low',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/%D0%A1%D0%B0%D1%84%D1%96%D0%B9%D1%81%D0%BA%D1%96_%D1%81%D0%B0%D0%B1%D0%BE%D1%80%2C_%D0%9F%D0%BE%D0%BB%D0%B0%D1%86%D0%BA.jpg?width=900',
  ARRAY['собор', 'культура', 'история']
),
(
  'Лидский замок',
  'Лида',
  'улица Замковая, 1',
  'history',
  'Средневековый замок князя Гедимина, восстановленный для экскурсий и событий.',
  53.887500,
  25.302900,
  95,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/The_Lida_castle.JPG?width=900',
  ARRAY['замок', 'история', 'архитектура']
),
(
  'Мемориальный комплекс Хатынь',
  'Логойский район',
  'Хатынь',
  'history',
  'Мемориал на месте сожжённой деревни, посвящённый памяти жертв войны.',
  54.334600,
  27.943200,
  90,
  'free',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Khatyn%2C_Belarus_5.jpg?width=900',
  ARRAY['мемориал', 'история', 'память']
),
(
  'Гомельский дворцово-парковый ансамбль',
  'Гомель',
  'площадь Ленина, 4',
  'architecture',
  'Дворец Румянцевых и Паскевичей с парком, набережной Сожа и музейными залами.',
  52.422600,
  31.015900,
  120,
  'mid',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Gomel-dvorets_Rumyantsevyh-Paskevichei_-_zima2008.JPG?width=900',
  ARRAY['дворец', 'парк', 'архитектура']
),
(
  'Августовский канал',
  'Гродненский район',
  'Августовский канал',
  'nature',
  'Водно-парковый маршрут с шлюзами, лесами и прогулками вдоль канала.',
  53.862000,
  23.623200,
  150,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Augustow_Canal_IMG_1384_2175.jpg?width=900',
  ARRAY['природа', 'вода', 'прогулка']
),
(
  'Браславские озёра',
  'Браслав',
  'Национальный парк Браславские озёра',
  'nature',
  'Озёрный край с обзорными точками, тропами и спокойными природными маршрутами.',
  55.643000,
  27.040000,
  180,
  'low',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Belarus%2C_Braslav_lakes%2C_Strusto_1.jpg?width=900',
  ARRAY['озёра', 'природа', 'панорама']
),
(
  'Гродненский Старый замок',
  'Гродно',
  'улица Замковая, 22',
  'history',
  'Исторический замок над Неманом с музейной экспозицией и видами на город.',
  53.678400,
  23.823100,
  100,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Grodno_Old_Castle_11166_2150.jpg?width=900',
  ARRAY['замок', 'история', 'музей']
),
(
  'Витебская ратуша',
  'Витебск',
  'улица Ленина, 36',
  'architecture',
  'Историческая ратуша в центре Витебска, где расположен областной краеведческий музей.',
  55.194700,
  30.206900,
  80,
  'low',
  4.6,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Vitebsk_cityhall_oct_2005.jpg?width=900',
  ARRAY['ратуша', 'архитектура', 'музей']
),
(
  'Бобруйская крепость',
  'Бобруйск',
  'улица Карбышева',
  'history',
  'Крупный фортификационный комплекс XIX века с сохранившимися укреплениями.',
  53.137800,
  29.225100,
  85,
  'free',
  4.4,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Bobruisk_fortress.jpg?width=900',
  ARRAY['крепость', 'история', 'прогулка']
),
(
  'Буйничское поле',
  'Могилёв',
  'Буйничское поле',
  'history',
  'Мемориальный комплекс на месте оборонительных боёв под Могилёвом.',
  53.859700,
  30.267600,
  80,
  'free',
  4.5,
  'https://commons.wikimedia.org/wiki/Special:FilePath/%D0%91%D1%83%D0%B9%D0%BD%D0%B8%D1%87%D1%81%D0%BA%D0%BE%D0%B5_%D0%BF%D0%BE%D0%BB%D0%B5.jpg?width=900',
  ARRAY['мемориал', 'история', 'память']
),
(
  'Меловые карьеры у Волковыска',
  'Волковыск',
  'окрестности Волковыска',
  'nature',
  'Светлые меловые ландшафты и водоёмы, популярные для фотопрогулок.',
  53.151000,
  24.455000,
  90,
  'free',
  4.3,
  'https://commons.wikimedia.org/wiki/Special:FilePath/The_chalkpit_near_Krasnoselsk_-_panoramio.jpg?width=900',
  ARRAY['природа', 'панорама', 'фото']
)
ON CONFLICT (name, city) DO UPDATE SET
  address = EXCLUDED.address,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  duration_minutes = EXCLUDED.duration_minutes,
  budget_level = EXCLUDED.budget_level,
  rating = EXCLUDED.rating,
  image_url = EXCLUDED.image_url,
  tags = EXCLUDED.tags;

-- Европейские туристические объекты
INSERT INTO attractions (
  name, city, address, category, description, latitude, longitude,
  duration_minutes, budget_level, rating, image_url, tags
) VALUES
(
  'Вавельский замок',
  'Краков',
  'Wawel 5',
  'history',
  'Королевский замок на Вавельском холме, один из главных исторических символов Польши.',
  50.054000,
  19.935200,
  120,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Wawel_castle.jpg?width=900',
  ARRAY['польша', 'краков', 'замок', 'история']
),
(
  'Мальборкский замок',
  'Мальборк',
  'Starościńska 1',
  'history',
  'Огромная кирпичная крепость Тевтонского ордена на берегу Ногата.',
  54.039700,
  19.027800,
  150,
  'mid',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Panorama_of_Malbork_Castle.jpg?width=900',
  ARRAY['польша', 'мальборк', 'замок', 'крепость']
),
(
  'Рыночная площадь в Кракове',
  'Краков',
  'Rynek Główny',
  'culture',
  'Главная площадь старого Кракова с Суконными рядами, башней ратуши и уличной атмосферой.',
  50.061700,
  19.937300,
  80,
  'free',
  4.9,
  'https://upload.wikimedia.org/wikipedia/commons/1/18/Sukiennice_and_Main_Market_Square_Krakow_Poland.JPG',
  ARRAY['польша', 'краков', 'площадь', 'культура']
),
(
  'Соляная шахта Величка',
  'Величка',
  'Daniłowicza 10',
  'history',
  'Подземный музей с соляными камерами, часовнями и маршрутами по старинным шахтным выработкам.',
  49.983300,
  20.054200,
  150,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Chapel_of_St._Kinga%2C_Wieliczka_Salt_Mine_%282437283812%29.jpg/960px-Chapel_of_St._Kinga%2C_Wieliczka_Salt_Mine_%282437283812%29.jpg',
  ARRAY['польша', 'величка', 'шахта', 'музей']
),
(
  'Старе Място в Варшаве',
  'Варшава',
  'Plac Zamkowy',
  'history',
  'Восстановленный исторический центр Варшавы с Королевским замком, площадями и узкими улицами.',
  52.249700,
  21.012200,
  100,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/2018-07-08_Old_Town_Market_Square_in_Warsaw.jpg/960px-2018-07-08_Old_Town_Market_Square_in_Warsaw.jpg',
  ARRAY['польша', 'варшава', 'старый город', 'история']
),
(
  'Королевский замок в Варшаве',
  'Варшава',
  'Plac Zamkowy 4',
  'architecture',
  'Историческая королевская резиденция на Замковой площади с музейными залами и парадными интерьерами.',
  52.247900,
  21.014000,
  120,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/b/bb/Royal_Castle_in_Warsaw%2C_Poland%2C_2022%2C_03.jpg',
  ARRAY['польша', 'варшава', 'замок', 'архитектура']
),
(
  'Лазенковский парк',
  'Варшава',
  'Agrykola 1',
  'nature',
  'Большой дворцово-парковый ансамбль с прудами, аллеями, павильонами и памятником Шопену.',
  52.215300,
  21.035500,
  120,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Palace_on_the_Isle_-_panoramio.jpg/960px-Palace_on_the_Isle_-_panoramio.jpg',
  ARRAY['польша', 'варшава', 'парк', 'природа']
),
(
  'Дворец культуры и науки',
  'Варшава',
  'Plac Defilad 1',
  'architecture',
  'Высотное здание в центре Варшавы с обзорной площадкой, выставками и городскими панорамами.',
  52.231900,
  21.006700,
  70,
  'mid',
  4.6,
  'https://upload.wikimedia.org/wikipedia/commons/b/b0/Pa%C5%82ac_Kultury_i_Nauki_2019.jpg',
  ARRAY['польша', 'варшава', 'панорама', 'архитектура']
),
(
  'Европейский центр Солидарности',
  'Гданьск',
  'Plac Solidarności 1',
  'culture',
  'Современный музей и культурный центр, посвящённый движению Солидарность и новейшей истории Польши.',
  54.361900,
  18.649700,
  110,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/6/6a/European_Solidarity_Centre_2015_003.jpg',
  ARRAY['польша', 'гданьск', 'музей', 'история']
),
(
  'Длинный рынок в Гданьске',
  'Гданьск',
  'Długi Targ',
  'architecture',
  'Главная городская улица и площадь старого Гданьска с фонтаном Нептуна и фасадами купеческих домов.',
  54.348800,
  18.653300,
  75,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Gda%C5%84sk_D%C5%82ugi_Targ%2C_Fontanna_Neptuna.jpg/960px-Gda%C5%84sk_D%C5%82ugi_Targ%2C_Fontanna_Neptuna.jpg',
  ARRAY['польша', 'гданьск', 'старый город', 'архитектура']
),
(
  'Остров Тумский во Вроцлаве',
  'Вроцлав',
  'Ostrów Tumski',
  'culture',
  'Старейшая часть Вроцлава с соборами, мостами, набережными и вечерней подсветкой фонарей.',
  51.114200,
  17.046100,
  90,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Wroclaw_-_Ostrow_Tumski.jpg/960px-Wroclaw_-_Ostrow_Tumski.jpg',
  ARRAY['польша', 'вроцлав', 'собор', 'культура']
),
(
  'Познанская ратуша',
  'Познань',
  'Stary Rynek 1',
  'architecture',
  'Ренессансная ратуша на Старом рынке Познани, известная историческими интерьерами и городскими легендами.',
  52.408300,
  16.934200,
  70,
  'low',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/0/03/Ayuntamiento%2C_Poznan%2C_Polonia%2C_2019-12-18%2C_DD_04-06_HDR.jpg',
  ARRAY['польша', 'познань', 'ратуша', 'архитектура']
),
(
  'Ясная Гора',
  'Ченстохова',
  'Kordeckiego 2',
  'culture',
  'Крупный монастырский комплекс и важный паломнический центр с богатой историей и музейными залами.',
  50.812000,
  19.097200,
  120,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/d/d1/Cz%C4%99stochowa_klasztor_Jasna_G%C3%B3ra-2162.jpg',
  ARRAY['польша', 'ченстохова', 'монастырь', 'культура']
),
(
  'Морское Око',
  'Закопане',
  'Tatrzański Park Narodowy',
  'nature',
  'Горное озеро в Татрах с пешеходными маршрутами, видами на вершины и природными панорамами.',
  49.197900,
  20.070600,
  180,
  'low',
  4.9,
  'https://upload.wikimedia.org/wikipedia/commons/6/62/Morskie_Oko_08_VIII_2004-0015.jpg',
  ARRAY['польша', 'закопане', 'татры', 'природа']
),
(
  'Бранденбургские ворота',
  'Берлин',
  'Pariser Platz',
  'architecture',
  'Неоклассические ворота в центре Берлина и символ объединения Германии.',
  52.516300,
  13.377700,
  45,
  'free',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Brandenburger_Tor_abends.jpg?width=900',
  ARRAY['германия', 'берлин', 'архитектура', 'символ']
),
(
  'Замок Нойшванштайн',
  'Швангау',
  'Neuschwansteinstraße 20',
  'history',
  'Романтический замок Людвига II на фоне альпийских склонов.',
  47.557600,
  10.749800,
  150,
  'high',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Schloss-Neuschwanstein.jpg?width=900',
  ARRAY['германия', 'бавария', 'замок', 'горы']
),
(
  'Рейхстаг',
  'Берлин',
  'Platz der Republik 1',
  'architecture',
  'Историческое здание парламента Германии со стеклянным куполом и видом на центр Берлина.',
  52.518600,
  13.376200,
  90,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/0/0d/Berlin_reichstag_west_panorama_2.jpg',
  ARRAY['германия', 'берлин', 'парламент', 'архитектура']
),
(
  'Берлинский кафедральный собор',
  'Берлин',
  'Am Lustgarten',
  'culture',
  'Монументальный собор на Музейном острове с куполом, интерьерами и панорамной галереей.',
  52.519100,
  13.401000,
  90,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/8/84/141227_Berliner_Dom.jpg',
  ARRAY['германия', 'берлин', 'собор', 'культура']
),
(
  'Музейный остров',
  'Берлин',
  'Museumsinsel',
  'culture',
  'Комплекс крупных музеев на острове Шпрее с античными коллекциями, искусством и архитектурой.',
  52.516900,
  13.401900,
  180,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/c/c9/Berlin_Museumsinsel_Fernsehturm.jpg',
  ARRAY['германия', 'берлин', 'музей', 'культура']
),
(
  'East Side Gallery',
  'Берлин',
  'Mühlenstraße',
  'culture',
  'Открытая галерея на сохранившемся участке Берлинской стены с известными муралами.',
  52.505000,
  13.439400,
  70,
  'free',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/2/2b/Segment_with_Graffiti_of_the_Berlin_Wall_%283_of_4%29_%28cropped%29.jpg',
  ARRAY['германия', 'берлин', 'стрит-арт', 'история']
),
(
  'Кёльнский собор',
  'Кёльн',
  'Domkloster 4',
  'architecture',
  'Готический собор у главного вокзала Кёльна, один из самых узнаваемых храмов Европы.',
  50.941300,
  6.958300,
  120,
  'free',
  4.9,
  'https://upload.wikimedia.org/wikipedia/commons/0/04/K%C3%B6lner_Dom_-_Westfassade_2022_ohne_Ger%C3%BCst-0968_b.jpg',
  ARRAY['германия', 'кёльн', 'собор', 'архитектура']
),
(
  'Гейдельбергский замок',
  'Гейдельберг',
  'Schlosshof 1',
  'history',
  'Романтические руины замка над старым городом Гейдельберга с террасами и видом на Неккар.',
  49.410600,
  8.715300,
  130,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/1/1d/Heidelberg-2726936.jpg',
  ARRAY['германия', 'гейдельберг', 'замок', 'история']
),
(
  'Миниатюрная страна чудес',
  'Гамбург',
  'Kehrwieder 2',
  'culture',
  'Большой музей железнодорожных и городских миниатюр в историческом районе Шпайхерштадт.',
  53.543900,
  9.989400,
  150,
  'mid',
  4.9,
  'https://upload.wikimedia.org/wikipedia/commons/f/fc/Miniatur_wunderland.jpg',
  ARRAY['германия', 'гамбург', 'музей', 'семья']
),
(
  'Эльбская филармония',
  'Гамбург',
  'Platz der Deutschen Einheit 4',
  'architecture',
  'Современный концертный зал на берегу Эльбы с общественной смотровой площадкой и видом на порт.',
  53.541300,
  9.984100,
  80,
  'free',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/c/c2/Elbphilharmonie_2025.jpg',
  ARRAY['германия', 'гамбург', 'филармония', 'архитектура']
),
(
  'Мариенплац',
  'Мюнхен',
  'Marienplatz',
  'architecture',
  'Центральная площадь Мюнхена с Новой ратушей, башнями и оживлённой городской атмосферой.',
  48.137400,
  11.575500,
  70,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/7/73/Rathaus_and_Marienplatz_from_Peterskirche_-_August_2006.jpg',
  ARRAY['германия', 'мюнхен', 'площадь', 'архитектура']
),
(
  'Английский сад',
  'Мюнхен',
  'Englischer Garten',
  'nature',
  'Один из крупнейших городских парков Европы с прогулочными дорожками, лугами и ручьём Айсбах.',
  48.164200,
  11.605200,
  120,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/b/bc/Aerial_image_of_Englischer_Garten_in_Munich_%28view_from_the_southwest%29.jpg',
  ARRAY['германия', 'мюнхен', 'парк', 'природа']
),
(
  'Дворец Сан-Суси',
  'Потсдам',
  'Maulbeerallee',
  'architecture',
  'Летняя резиденция Фридриха Великого с террасными садами, павильонами и дворцовым парком.',
  52.403300,
  13.038600,
  150,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/8/8b/Schloss_Sanssouci_2014.jpg',
  ARRAY['германия', 'потсдам', 'дворец', 'сад']
),
(
  'Фрауэнкирхе в Дрездене',
  'Дрезден',
  'Neumarkt',
  'architecture',
  'Восстановленный барочный храм на площади Ноймаркт, ставший символом исторического центра Дрездена.',
  51.051900,
  13.741600,
  80,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/9/93/100130_150006_Dresden_Frauenkirche_winter_blue_sky-2.jpg',
  ARRAY['германия', 'дрезден', 'собор', 'архитектура']
),
(
  'Цвингер',
  'Дрезден',
  'Sophienstraße',
  'culture',
  'Барочный дворцовый комплекс с галереями, павильонами, фонтанами и музейными коллекциями.',
  51.053000,
  13.734700,
  120,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/2/29/2006-07-30_Zwinger_dresden2.jpg',
  ARRAY['германия', 'дрезден', 'дворец', 'музей']
),
(
  'Рёмерберг',
  'Франкфурт-на-Майне',
  'Römerberg',
  'history',
  'Историческая площадь Франкфурта с ратушей Рёмер, фахверковыми фасадами и городскими событиями.',
  50.110600,
  8.682200,
  70,
  'free',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/R%C3%B6merberg_Frankfurt_abends.jpg/960px-R%C3%B6merberg_Frankfurt_abends.jpg',
  ARRAY['германия', 'франкфурт', 'площадь', 'история']
),
(
  'Нюрнбергская крепость',
  'Нюрнберг',
  'Burg 17',
  'history',
  'Средневековый крепостной комплекс над старым городом Нюрнберга с башнями и обзорными точками.',
  49.457700,
  11.075500,
  110,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/5/50/Nuernberg_Burg_Panorama_PtGUI.jpg',
  ARRAY['германия', 'нюрнберг', 'крепость', 'история']
),
(
  'Эйфелева башня',
  'Париж',
  'Champ de Mars',
  'architecture',
  'Главный символ Парижа с обзорными площадками и видом на город.',
  48.858400,
  2.294500,
  120,
  'high',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/The_Eiffel_Tower.JPG?width=900',
  ARRAY['франция', 'париж', 'башня', 'панорама']
),
(
  'Лувр',
  'Париж',
  'Rue de Rivoli',
  'culture',
  'Один из крупнейших музеев мира с коллекциями искусства и историческим дворцом.',
  48.860600,
  2.337600,
  180,
  'high',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Inside_the_Louvre_Pyramid.jpg?width=900',
  ARRAY['франция', 'париж', 'музей', 'культура']
),
(
  'Собор Парижской Богоматери',
  'Париж',
  '6 Parvis Notre-Dame',
  'architecture',
  'Готический собор на острове Сите, один из главных исторических символов Парижа.',
  48.853000,
  2.349900,
  90,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/f/f7/Notre-Dame_de_Paris%2C_4_October_2017.jpg',
  ARRAY['франция', 'париж', 'собор', 'архитектура']
),
(
  'Триумфальная арка',
  'Париж',
  'Place Charles de Gaulle',
  'history',
  'Монумент на площади Шарля де Голля с обзорной площадкой и видом на Елисейские Поля.',
  48.873800,
  2.295000,
  60,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg',
  ARRAY['франция', 'париж', 'арка', 'история']
),
(
  'Сакре-Кёр',
  'Париж',
  '35 Rue du Chevalier de la Barre',
  'architecture',
  'Белая базилика на холме Монмартр с панорамой Парижа и оживлёнными улицами вокруг.',
  48.886700,
  2.343100,
  90,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/c/c5/Le_sacre_coeur.jpg',
  ARRAY['франция', 'париж', 'монмартр', 'архитектура']
),
(
  'Музей Орсе',
  'Париж',
  '1 Rue de la Légion d''Honneur',
  'culture',
  'Музей искусства XIX века в здании бывшего вокзала с коллекцией импрессионистов.',
  48.860000,
  2.326600,
  150,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Mus%C3%A9e_d%60Orsay_Paris_-_panoramio.jpg/960px-Mus%C3%A9e_d%60Orsay_Paris_-_panoramio.jpg',
  ARRAY['франция', 'париж', 'музей', 'искусство']
),
(
  'Версальский дворец',
  'Версаль',
  'Place d''Armes',
  'architecture',
  'Королевская резиденция с парадными залами, зеркальной галереей, садами и фонтанами.',
  48.804900,
  2.120400,
  180,
  'high',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/d/d2/Versailles-Chateau-Jardins02.jpg',
  ARRAY['франция', 'версаль', 'дворец', 'сад']
),
(
  'Пантеон',
  'Париж',
  'Place du Panthéon',
  'history',
  'Неоклассический мавзолей в Латинском квартале, где похоронены выдающиеся деятели Франции.',
  48.846200,
  2.346000,
  80,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/8/80/Pantheon_of_Paris_007.JPG',
  ARRAY['франция', 'париж', 'пантеон', 'история']
),
(
  'Сент-Шапель',
  'Париж',
  '10 Boulevard du Palais',
  'culture',
  'Готическая капелла с высокими витражами и камерным историческим интерьером.',
  48.855400,
  2.345000,
  60,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/7/70/Sainte_Chapelle_-_Upper_level_1.jpg',
  ARRAY['франция', 'париж', 'витражи', 'культура']
),
(
  'Опера Гарнье',
  'Париж',
  'Place de l''Opéra',
  'architecture',
  'Театр XIX века с богатыми интерьерами, парадной лестницей и фасадом в стиле боз-ар.',
  48.871900,
  2.331600,
  90,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/d/dc/Paris_Opera_full_frontal_architecture%2C_May_2009.jpg',
  ARRAY['франция', 'париж', 'опера', 'архитектура']
),
(
  'Мон-Сен-Мишель',
  'Мон-Сен-Мишель',
  'Abbaye du Mont-Saint-Michel',
  'history',
  'Аббатство на приливном острове в Нормандии, окружённое стенами, улочками и морскими видами.',
  48.636100,
  -1.511500,
  180,
  'mid',
  4.9,
  'https://upload.wikimedia.org/wikipedia/commons/7/78/Mont-Saint-Michel_vu_du_ciel.jpg',
  ARRAY['франция', 'нормандия', 'аббатство', 'история']
),
(
  'Замок Шамбор',
  'Шамбор',
  'Château de Chambord',
  'architecture',
  'Крупный замок эпохи Возрождения в долине Луары с башнями, террасами и лесным парком.',
  47.616100,
  1.517000,
  150,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/1/1f/Aerial_image_of_Ch%C3%A2teau_de_Chambord_%28view_from_the_southeast%29.jpg',
  ARRAY['франция', 'луара', 'замок', 'архитектура']
),
(
  'Замок Шенонсо',
  'Шенонсо',
  'Château de Chenonceau',
  'history',
  'Изящный замок над рекой Шер с садами, галереей и интерьерами эпохи Возрождения.',
  47.324900,
  1.070300,
  140,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/f/f7/Chateau_de_Chenonceau_2008E_%28adjusted2%29.jpg',
  ARRAY['франция', 'луара', 'замок', 'история']
),
(
  'Крепость Каркассон',
  'Каркассон',
  'Cité de Carcassonne',
  'history',
  'Средневековый укреплённый город с башнями, стенами и атмосферой юга Франции.',
  43.206100,
  2.363000,
  150,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/2/25/1_carcassonne_aerial_2016.jpg',
  ARRAY['франция', 'каркассон', 'крепость', 'история']
),
(
  'Пон-дю-Гар',
  'Вер-Пон-дю-Гар',
  'Pont du Gard',
  'history',
  'Древнеримский акведук над рекой Гардон, сохранившийся как впечатляющий инженерный памятник.',
  43.947600,
  4.535000,
  100,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/4/42/Pont_du_Gard_BLS.jpg',
  ARRAY['франция', 'прованс', 'акведук', 'история']
),
(
  'Папский дворец',
  'Авиньон',
  'Place du Palais',
  'history',
  'Готический дворец пап в Авиньоне с крепостными фасадами, залами и видами на город.',
  43.950900,
  4.807500,
  120,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/f/fc/Avignon_Palais_des_Papes_2013.jpg',
  ARRAY['франция', 'авиньон', 'дворец', 'история']
),
(
  'Променад дез Англе',
  'Ницца',
  'Promenade des Anglais',
  'nature',
  'Знаменитая набережная Ниццы вдоль Лазурного берега с пляжами и морскими видами.',
  43.695000,
  7.265000,
  90,
  'free',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/6/60/CollineDuChateau_NiceFrance2022.png',
  ARRAY['франция', 'ницца', 'море', 'природа']
),
(
  'Старый Лион',
  'Лион',
  'Vieux Lyon',
  'culture',
  'Исторический квартал Лиона с ренессансными домами, узкими проходами и гастрономическими улицами.',
  45.762100,
  4.827500,
  110,
  'free',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/4/4b/Vieuxlyon_saintjean_toits.jpg',
  ARRAY['франция', 'лион', 'старый город', 'культура']
),
(
  'Страсбургский собор',
  'Страсбург',
  'Place de la Cathédrale',
  'architecture',
  'Готический собор из розового песчаника с высокой башней, астрономическими часами и площадью вокруг.',
  48.581900,
  7.750300,
  100,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/7/7e/Strasbourg_Cathedral_Exterior_-_Diliff.jpg',
  ARRAY['франция', 'страсбург', 'собор', 'архитектура']
),
(
  'Дюна Пила',
  'Ла-Тест-де-Бюш',
  'Dune du Pilat',
  'nature',
  'Самая высокая песчаная дюна Европы у Атлантического океана с видом на залив Аркашон.',
  44.589200,
  -1.214700,
  120,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/d/d4/DunePyla.JPG',
  ARRAY['франция', 'атлантика', 'дюна', 'природа']
),
(
  'Колизей',
  'Рим',
  'Piazza del Colosseo',
  'history',
  'Античный амфитеатр и один из самых узнаваемых символов Рима.',
  41.890200,
  12.492200,
  120,
  'high',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Colosseum_Rome_.jpg?width=900',
  ARRAY['италия', 'рим', 'античность', 'история']
),
(
  'Пизанская башня',
  'Пиза',
  'Piazza del Duomo',
  'architecture',
  'Знаменитая наклонная колокольня на площади Чудес.',
  43.723000,
  10.396600,
  90,
  'mid',
  4.7,
  'https://commons.wikimedia.org/wiki/Special:FilePath/The_Leaning_Tower_of_Pisa.jpg?width=900',
  ARRAY['италия', 'пиза', 'башня', 'архитектура']
),
(
  'Саграда Фамилия',
  'Барселона',
  'Carrer de Mallorca 401',
  'architecture',
  'Базилика Антонио Гауди с необычной архитектурой и продолжающимся строительством.',
  41.403600,
  2.174400,
  130,
  'high',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Sagrada_Familia_.jpg?width=900',
  ARRAY['испания', 'барселона', 'гауди', 'архитектура']
),
(
  'Альгамбра',
  'Гранада',
  'Calle Real de la Alhambra',
  'history',
  'Дворцово-крепостной комплекс с садами, двориками и исламской архитектурой.',
  37.176100,
  -3.588100,
  180,
  'high',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Alhambra_de_Granada_2024.jpg?width=900',
  ARRAY['испания', 'гранада', 'дворец', 'история']
),
(
  'Парк Гуэль',
  'Барселона',
  'Carrer d''Olot',
  'culture',
  'Парк Антонио Гауди с мозаиками, террасами, сказочной архитектурой и видами на Барселону.',
  41.414500,
  2.152700,
  120,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/3/33/Parc_guell_-_panoramio.jpg',
  ARRAY['испания', 'барселона', 'гауди', 'парк']
),
(
  'Дом Бальо',
  'Барселона',
  'Passeig de Gràcia 43',
  'architecture',
  'Яркий городской дом Гауди с волнистым фасадом, мозаикой и необычными интерьерами.',
  41.391700,
  2.164900,
  90,
  'high',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/b/bf/Casa_Batllo_Overview_Barcelona_Spain_cut.jpg',
  ARRAY['испания', 'барселона', 'гауди', 'архитектура']
),
(
  'Готический квартал Барселоны',
  'Барселона',
  'Barri Gòtic',
  'history',
  'Старинный район с узкими улицами, площадями, средневековой застройкой и атмосферой старого города.',
  41.383900,
  2.176300,
  100,
  'free',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/6/6d/Barcelona_-_Carrer_del_Bisbe.jpg',
  ARRAY['испания', 'барселона', 'старый город', 'история']
),
(
  'Королевский дворец в Мадриде',
  'Мадрид',
  'Calle de Bailén',
  'architecture',
  'Официальная королевская резиденция с парадными залами, оружейной палатой и площадью перед дворцом.',
  40.417900,
  -3.714300,
  130,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/9/9b/Palacio_Real_de_Madrid_Julio_2016_%28cropped%29.jpg',
  ARRAY['испания', 'мадрид', 'дворец', 'архитектура']
),
(
  'Музей Прадо',
  'Мадрид',
  'Paseo del Prado',
  'culture',
  'Крупный художественный музей с коллекциями Веласкеса, Гойи, Эль Греко и европейской живописи.',
  40.413800,
  -3.692100,
  160,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/6/68/Museo_del_Prado_2016_%2825185969599%29.jpg',
  ARRAY['испания', 'мадрид', 'музей', 'искусство']
),
(
  'Площадь Пласа-Майор',
  'Мадрид',
  'Plaza Mayor',
  'architecture',
  'Историческая площадь Мадрида с аркадами, фасадами, кафе и городскими событиями.',
  40.415400,
  -3.707400,
  60,
  'free',
  4.6,
  'https://upload.wikimedia.org/wikipedia/commons/d/d2/Madrid_Plaza_Mayor_%2848733706273%29.jpg',
  ARRAY['испания', 'мадрид', 'площадь', 'архитектура']
),
(
  'Парк Ретиро',
  'Мадрид',
  'Plaza de la Independencia',
  'nature',
  'Большой городской парк с озером, аллеями, Хрустальным дворцом и спокойными прогулочными маршрутами.',
  40.415300,
  -3.684400,
  110,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/2/2b/MADRID_051116_MXALX_041.jpg',
  ARRAY['испания', 'мадрид', 'парк', 'природа']
),
(
  'Севильский кафедральный собор',
  'Севилья',
  'Avenida de la Constitución',
  'architecture',
  'Огромный готический собор с башней Хиральда, внутренним двором и богатым историческим наследием.',
  37.386100,
  -5.992600,
  120,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/2/2b/Sevilla_Cathedral_-_Southeast.jpg',
  ARRAY['испания', 'севилья', 'собор', 'архитектура']
),
(
  'Алькасар Севильи',
  'Севилья',
  'Patio de Banderas',
  'history',
  'Королевский дворец с мавританской архитектурой, внутренними дворами, садами и декоративными залами.',
  37.383100,
  -5.990300,
  140,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/c/c9/Sevilla-2-2_%2848040287512%29-edit.jpg',
  ARRAY['испания', 'севилья', 'дворец', 'история']
),
(
  'Мескита Кордовы',
  'Кордова',
  'Calle Cardenal Herrero',
  'culture',
  'Собор-мечеть с аркадами, колоннами и уникальным сочетанием исламской и христианской архитектуры.',
  37.879000,
  -4.779400,
  120,
  'mid',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/6/6c/Mezquita_de_C%C3%B3rdoba_desde_el_aire_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29.jpg',
  ARRAY['испания', 'кордова', 'собор', 'культура']
),
(
  'Город искусств и наук',
  'Валенсия',
  'Av. del Professor López Piñero',
  'architecture',
  'Футуристический комплекс Валенсии с музеем науки, океанариумом, павильонами и водными зеркалами.',
  39.454800,
  -0.350500,
  150,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/El_Hemisf%C3%A9rico%2C_Ciudad_de_las_Artes_y_las_Ciencias%2C_Valencia%2C_Espa%C3%B1a%2C_2014-06-29%2C_DD_71.JPG/960px-El_Hemisf%C3%A9rico%2C_Ciudad_de_las_Artes_y_las_Ciencias%2C_Valencia%2C_Espa%C3%B1a%2C_2014-06-29%2C_DD_71.JPG',
  ARRAY['испания', 'валенсия', 'архитектура', 'музей']
),
(
  'Музей Гуггенхайма в Бильбао',
  'Бильбао',
  'Abandoibarra Etorbidea 2',
  'culture',
  'Музей современного искусства в выразительном здании Фрэнка Гери на берегу реки Нервьон.',
  43.268700,
  -2.934000,
  130,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/c/c7/Museo_Guggenheim%2C_Bilbao_%2831273245344%29.jpg',
  ARRAY['испания', 'бильбао', 'музей', 'архитектура']
),
(
  'Собор Сантьяго-де-Компостела',
  'Сантьяго-де-Компостела',
  'Praza do Obradoiro',
  'culture',
  'Главный собор паломнического пути Святого Иакова с барочным фасадом и исторической площадью.',
  42.880600,
  -8.544600,
  120,
  'free',
  4.8,
  'https://upload.wikimedia.org/wikipedia/commons/a/a9/Santiago_cathedral_2021.jpg',
  ARRAY['испания', 'сантьяго', 'собор', 'культура']
),
(
  'Алькасар Сеговии',
  'Сеговия',
  'Plaza Reina Victoria Eugenia',
  'history',
  'Замок на скале у старого города Сеговии с башнями, залами и видом на кастильские пейзажи.',
  40.952500,
  -4.132900,
  100,
  'mid',
  4.7,
  'https://upload.wikimedia.org/wikipedia/commons/4/40/Panor%C3%A1mica_Oto%C3%B1o_Alc%C3%A1zar_de_Segovia.jpg',
  ARRAY['испания', 'сеговия', 'замок', 'история']
),
(
  'Дворец Шёнбрунн',
  'Вена',
  'Schönbrunner Schloßstraße 47',
  'architecture',
  'Императорская резиденция Габсбургов с садами, залами и павильонами.',
  48.184500,
  16.312200,
  180,
  'high',
  4.8,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Schonbrunn_Palace_-_Vienna.jpg?width=900',
  ARRAY['австрия', 'вена', 'дворец', 'сад']
),
(
  'Маттерхорн',
  'Церматт',
  'Matterhorn',
  'nature',
  'Знаменитая альпийская вершина у Церматта с панорамными маршрутами.',
  45.976300,
  7.658600,
  180,
  'high',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Matterhorn_%286888207113%29.jpg?width=900',
  ARRAY['швейцария', 'альпы', 'горы', 'природа']
),
(
  'Карлов мост',
  'Прага',
  'Karlův most',
  'architecture',
  'Исторический каменный мост через Влтаву со скульптурами и видами на Прагу.',
  50.086500,
  14.411400,
  70,
  'free',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/The_Charles_Bridge%2C_Prague..jpg?width=900',
  ARRAY['чехия', 'прага', 'мост', 'архитектура']
),
(
  'Пражский Град',
  'Прага',
  'Pražský hrad',
  'history',
  'Крупный замковый комплекс с дворцами, соборами и видами на город.',
  50.091100,
  14.401600,
  160,
  'mid',
  4.9,
  'https://commons.wikimedia.org/wiki/Special:FilePath/Prague_Castle.jpg?width=900',
  ARRAY['чехия', 'прага', 'замок', 'история']
)
ON CONFLICT (name, city) DO UPDATE SET
  address = EXCLUDED.address,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  duration_minutes = EXCLUDED.duration_minutes,
  budget_level = EXCLUDED.budget_level,
  rating = EXCLUDED.rating,
  image_url = EXCLUDED.image_url,
  tags = EXCLUDED.tags;
